### ISSUE TITLE
Reinforcement Learning: Is there a way to train again already trained NeuralNet with new input training set? It seems `keepNetworkIntact` works incorrectly

### ISSUE THREAD

**Issue by Nickproger** [BrainJS/brain.js#83] opened 2017-08-18 11:46 UTC
```js
var net = new brain.NeuralNetwork();

net.train([
	{input: [0, 0], output: [0]},
	{input: [1, 1], output: [0]}
 ]);

// train again with other input data set
net.train([
	{input: [0, 1], output: [1]},
	{input: [1, 0], output: [1]},
], {keepNetworkIntact:true});

console.log(net.run([0, 0]), 'expect to be near 1');
console.log(net.run([1, 0]), 'expect to be near 0');
console.log(net.run([0, 1]), 'expect to be near 0');
console.log(net.run([1, 1]), 'expect to be near 1');

```

current result:
```
[0.928556545785631] "expect to be near 1"
[0.930771916408008] "expect to be near 0"
[0.9286057351606157] "expect to be near 0"
[0.9308093602969948] "expect to be near 1"
```

expected result:
```
[0.928556545785631] "expect to be near 1"
[near zero] "expect to be near 0"
[near zero] "expect to be near 0"
[0.9308093602969948] "expect to be near 1"
```

**Comment by robertleeplummerjr** [comment] 2017-08-25 15:42
Duplicate of: https://github.com/harthur-org/brain.js/issues/82

**Closed as completed by robertleeplummerjr** 2017-08-25 15:42 UTC
