### ISSUE TITLE
net.run() doesn't work with Node.js

### ISSUE THREAD

**Issue by TaPSus** [BrainJS/brain.js#453] opened 2019-09-18 21:15 UTC
Hey guys,

I tinker around with the RNNTimeStep model. Worked fine for me in Browser with plain JS and HTML, but now I want to create a serious application with Node.js. I installed brain.js via NPM and call the app with a .bat file, like this:

`node main.js`

and in my app, I declare the network like this:

```
  const config = {
    inputSize: 1,
    inputRange: 3,
    hiddenLayers: [10, 10],
    outputSize: 1,
    learningRate: 0.01,
    decayRate: 0.999
  };

  const net = new brain.recurrent.RNNTimeStep( config );
```
Just CopyPasta from the tutorial section. the `net.train()` function seems to work fine, but if I call `net.run() `or `net.toFunction().toString();` it gives me this error

```
C:\Users\Groudon\node_modules\brain.js\src\recurrent\rnn.js:287
    if (this.model.equations.length === 0) {
                   ^

TypeError: Cannot read property 'equations' of null
    at RNNTimeStep.get isRunnable [as isRunnable] (C:\Users\Groudon\node_modules\brain.js\src\recurrent\rnn.js:287:20)
    at RNNTimeStep.runNumbers (C:\Users\Groudon\node_modules\brain.js\src\recurrent\rnn-time-step.js:249:15)
    at RNNTimeStep.run (C:\Users\Groudon\node_modules\brain.js\src\recurrent\rnn-time-step.js:107:19)
    at Object.<anonymous> (C:\Users\Groudon\Desktop\BRAIN JS\main.js:52:27)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
```

Changing the config values for the net didn't work. Any suggestions?

- Cheers

**Comment by robertleeplummerjr** [comment] 2019-09-18 22:10
How are you running `.run()`?

**Comment by TaPSus** [comment] 2019-09-19 19:40
I tried this:

`console.log(String( net.run([1,1,0]) ));`

just the execute like this:

`net.run([1,1,0]);`

doesn't work too. If I try to generate the model class for save:

`require('fs').writeFileSync('savedModel.txt', String(net.toFunction().toString()) );`

exact the same error. It says that the property equations is null. I looked in the code, but didn't find something strange - but you know the code more well than me, maybe you can find a solution ^^ In the meanwhile I will try different network models and reply again.

**Comment by TaPSus** [comment] 2019-09-19 21:03
I solved the problem. It was caused by lazy coding from me. I gave the train() method accidently strings, instead of ints. The train process doesn't broke up, but if the run() method is called, there is just a not trained model. Anyway, it is working now. Except the toFunction() thing. Don't know why, but there is no data saved. If I can figure this out, I will reply again.

**Comment by robertleeplummerjr** [comment] 2019-09-19 23:24
Do you have a reproduction script?  That would be very helpful.

**Comment by aymather** [comment] 2020-05-14 18:56
I am also having trouble with `.run()`. I don't think I'm having the same issue, but I still can't figure it out.

I'm training a very basic model, trying to predict if a string is a youtube screen_name or id. Here's my script.

```
const brain = require('brain.js');
const fs = require('fs');

const encode = str => {
    var coded = [];
    for(let i = 0; i < str.length; i++) {
        coded.push(str.charCodeAt(i) / 255);
    }
    return coded
}

// create a simple feed forward neural network with backpropagation
const net = new brain.recurrent.LSTM()

const data = [
    {
        input: encode("neworder"),
        output: "screen_name"
    },
    {
        input: encode("OfficialSabbath"),
        output: "screen_name"
    },
    {
        input: encode("DepecheModeVEVO"),
        output: "screen_name"
    },
    {
        input: encode("PowerfulJRE"),
        output: "screen_name"
    },
    {
        input: encode("FrankSinatra"),
        output: "screen_name"
    },
    {
        input: encode("gratefuldead"),
        output: "screen_name"
    },
    {
        input: encode("greenday"),
        output: "screen_name"
    },
    {
        input: encode("KateBushMusic"),
        output: "screen_name"
    },
    {
        input: encode("madonna"),
        output: "screen_name"
    },
    {
        input: encode("MetallicaTV"),
        output: "screen_name"
    },
    {
        input: encode("UCSJ4gkVC6NrvII8umztf0Ow"),
        output: "id"
    },
    {
        input: encode("UCrTC0tOY5aujQFYDRf65xiw"),
        output: "id"
    },
    {
        input: encode("UCzQUP1qoWDoEbmsQxvdjxgQ"),
        output: "id"
    },
    {
        input: encode("UCuP2vJ6kRutQBfRmdcI92mA"),
        output: "id"
    },
    {
        input: encode("UCP9GKAbvDxLBqCcEaw4HDiw"),
        output: "id"
    },
    {
        input: encode("UC2D6eRvCeMtcF5OGHf1-trw"),
        output: "id"
    },
    {
        input: encode("UC5WjFrtBdufl6CZojX3D8dQ"),
        output: "id"
    },
    {
        input: encode("UC29ju8bIPH5as8OGnQzwJyA"),
        output: "id"
    },
    {
        input: encode("UCsBjURrPoezykLs9EqgamOA"),
        output: "id"
    },
    {
        input: encode("UCJLpammGMzjc4A2RfBVMbOg"),
        output: "id"
    }
]

net.train(data, { iterations: 2000, log: true });
fs.writeFileSync('./network.json', JSON.stringify(net.toJSON()), null, 2);

// const networkData = JSON.parse(fs.readFileSync('./network.json'));
// net.fromJSON(networkData);

const output = net.run(encode("PewDiePie"));
console.log(output);
```

My problem is that when I log the output, many times it gives me something very different than an output that I've set. Here's an example output.

```
alecmather in ~/Desktop/Projects/youtube-ai  > node index
creen_name
alecmather in ~/Desktop/Projects/youtube-ai  > node index
creen_name
alecmather in ~/Desktop/Projects/youtube-ai  > node index
0.38431372549019610.30980392156862746screen_name
alecmather in ~/Desktop/Projects/youtube-ai  > node index
0.38431372549019610.30980392156862746screen_name
alecmather in ~/Desktop/Projects/youtube-ai  > 
```

As you can see, it's giving me `creen_name` instead of `screen_name`, adding these weird decimals before the result. Sometimes I've gotten what seems like random strings such as `XvrTl5s`. And sometimes it logs nothing at all, like an empty string.

I'm running Node.js `v12.16.3`

**Comment by robertleeplummerjr** [comment] 2022-04-13 18:32
`.run()` works as intended in Brain.js version 2.0.0-beta.14.  Try that and see if you can reproduce.  Likely this was a bug that was resolved with unit tests, oh which there are now many.

**Closed as completed by robertleeplummerjr** 2022-04-13 18:32 UTC
Labels: discussion, needs more info
