### ISSUE TITLE
M1 Mac, nodejs GPU train time way longer than CPU

### ISSUE THREAD

**Issue by joshstrike** [BrainJS/brain.js#818] opened 2022-07-08 23:18 UTC
![A GIF or MEME to give some spice of the internet](https://i.pinimg.com/736x/63/b6/4e/63b64eab5d6b7aed46c1aa7809c9052b--kool-snails.jpg)

## _What_ is wrong?

Running the basic XOR example, 10k interations. With brain.NeuralNetwork(), 46 milliseconds. With brain.NeuralNetworkGPU(), 14.6 seconds.

## _Where_ does it happen?

brain.js@2.0.0-beta.15. Node 18.3.0 running on the command line, Python 3.9.13 (don't think this matters?), M1 Macbook Pro (Max, 32 GPU cores).

## _How_ do we replicate the issue?

1 - Run the first XOR example in the Readme.md, (speed shown was attained using default config options, not passing a config to NeuralNetwork()).

## Expected behavior (i.e. solution)

The GPU version... shouldn't be ...slower?

### Nodejs:

Node 18.3.0

### Browser:

N/A

### Brain.js:

brain.js@2.0.0-beta.15

## _How_ important is this (1-5)?

5 if it's a bug, 0 if it's a mistake on my end.

## Other Comments

This is my first time trying brain.js so it's quite possible I've just got something misconfigured. Love the project and the ease of use! The fact that on CPU that training took 46ms is hard to believe.

As a side note, I was unable to get the browser version to work at all from the CDN, it kept throwing `js_gpu is undefined` or something along those lines, then when I side-loaded gpu.js I got `js_gpu.GPU is not a constructor`. I'd rather use it in Node anyway...

**Comment by robertleeplummerjr** [comment] 2022-07-09 01:33
XOR uses approximately 3 neurons.  It will always be faster on CPU.  For GPU to break even you need something like 512x512 neurons.  This is a limitation of hardware and not a bug.  However the browser issue you raised may be legitimate.  Did you load GPU.js prior to brain.js in a browser?

**Comment by joshstrike** [comment] 2022-07-09 04:44
I tried both ways, initially just loading brain.js from the CDN:
`gpu_js is undefined`

then adding a script tag before first to load from https://unpkg.com/gpu.js@latest/dist/gpu-browser.min.js results in:
gpu_js.GPU is not a constructor @ brain.js:5460
`this.gpu = new gpu_js.GPU({ mode: options.mode });`

Same results in both Chrome and Firefox. gpu.js as loaded off the CDN looks like an ES module (loading it `type="module"` doesn't change anything, though).

Just out of curiosity, is the minimum time to run on the GPU a result of uploading batches of data, or modifying kernels with each epoch or both?

**Comment by robertleeplummerjr** [comment] 2022-07-09 12:15
The data is first uploaded (and a tiny compiled kernel for uploading training data) and then the kernels are compiled in the first iteration of learning.  After that everything exists and is ran from the GPU.

**Comment by joshstrike** [comment] 2022-07-09 22:13
Ahha, I didn't realize the hidden layers were where the advantage was. The trade-off point seems to be around [128,128]. With 512 rows of training data, benchmark on the M1 is about 11 seconds for both CPU and GPU at that size. Beyond that GPU takes off =)

**Comment by robertleeplummerjr** [comment] 2024-07-10 19:33
Closing this issue because of having a sufficient explanation.

**Closed as completed by robertleeplummerjr** 2024-07-10 19:33 UTC
Labels: bug
