### ISSUE TITLE
Error when calling trainAsync

### ISSUE THREAD

**Issue by ximik753** [BrainJS/brain.js#614] opened 2020-10-05 12:09 UTC
*What* is wrong?
When I try to call the trainAsync method, I get a strange error in the console [Object object]

## *How* do we replicate the issue?
Sample code where a similar issue occurs: https://codepen.io/ximik753/pen/pobzJgQ

**Comment by mubaidr** [comment] 2020-10-05 16:44
Confirmed. Looks like bug in one of the dependency. 

```bash
TypeError: _thaw2.default is not a constructor
 in brain.js/dist/neural-network.js — line 599
```

**Comment by tripolskypetr** [comment] 2021-03-08 14:33
I can suggest a hot fix. Open file `node_modules/brain.js/src/neural-network.js`. Then change the first line

```
const { Thaw } = require('thaw.js');
```

To this

```
const { Thaw } = require('thaw.js/dist');
```

**Comment by robertleeplummerjr** [comment] 2022-04-13 19:21
This is no longer an issue.  Here is a working example: https://observablehq.com/@robertleeplummerjr/brain-js-issue-614.

This was likely fixed with the conversion to typescript.  Tons of new tests.

**Closed as completed by robertleeplummerjr** 2022-04-13 19:21 UTC
Labels: bug, review
