### ISSUE TITLE
No TypeScript types :(

### ISSUE THREAD

**Issue by ali-habibzadeh** [BrainJS/brain.js#213] opened 2018-05-31 09:11 UTC
![https://i.imgur.com/o8fvxU0.png](https://i.imgur.com/o8fvxU0.png)

## *What* is wrong?
There is no .d.ts file for the library

## *Where* does it happen?
Happens when someone wants to use brain.js in a ts project

## *How* do we replicate the issue?
Start a ts project 

## *How* important is this (1-5)? 3.5
Many serious projects now take advantage of ts to write better code
https://trends.google.com/trends/explore?date=today%205-y&q=typescript

## Expected behavior (i.e. solution)
Please create types for your library

## Other Comments

**Comment by hellsan631** [comment] 2018-05-31 18:04
I might be wrong, but since there is an ES6 version in the pipeline, types should probably wait for that, because they would be outdated on that release. I was thinking of creating some TS and Flow types for the ES6 Version, as i've been using brain in a flow environment, and the types would be pretty neat to have.

Also, this is a dupe of https://github.com/BrainJS/brain.js/issues/182

**Comment by robertleeplummerjr** [comment] 2018-05-31 21:08
Will continue [here](https://github.com/BrainJS/brain.js/issues/182#issuecomment-393680819).  Collaboration would be very much so appreciated.

**Closed as completed by robertleeplummerjr** 2018-05-31 21:08 UTC
