### ISSUE TITLE
How I can continue training?

### ISSUE THREAD

**Issue by keyzog** [BrainJS/brain.js#84] opened 2017-08-24 19:13 UTC
Hi! I to want continue training my Neural Network from the same place where he finished his past training. How doing this?

I did try doing that:
```javascript
var net = new brain.recurrent.LSTM();

var json = JSON.parse(fs.readFileSync('data.json', 'utf-8'));
net.fromJSON(json);
var data = JSON.parse(fs.readFileSync('dialogs.json', 'utf-8'));

net.train(data, {
	errorThresh: 0.005,  // error threshold to reach
	iterations: 4,   // maximum training iterations
	log: true,           // console.log() progress periodically
	logPeriod: 1,       // number of iterations between logging
	learningRate: 0.3    // learning rate
});
```
But training starting with start. Can you help me?

P.S. Sorry for my bad English

**Comment by robertleeplummerjr** [comment] 2017-08-25 15:41
Duplicate of: https://github.com/harthur-org/brain.js/issues/82

**Closed as completed by robertleeplummerjr** 2017-08-25 15:41 UTC
